/// Project metadata for documentation generation
class ProjectInfo {
  final String name;
  final String version;
  final String description;
  final String stateLabel;
  final List<String> features;
  final List<String> dependencies;
  final List<String> endpoints;
  final String generatedDate;
  final String flutterVersion;
  final String dartVersion;

  const ProjectInfo({
    required this.name,
    required this.version,
    required this.description,
    required this.stateLabel,
    required this.features,
    required this.dependencies,
    required this.endpoints,
    required this.generatedDate,
    required this.flutterVersion,
    required this.dartVersion,
  });
}

class DocsTemplates {
  static String projectDocWord({
    required String projectName,
    required String version,
    required String stateLabel,
    String description = '',
    List<String> features = const [],
    List<String> dependencies = const [],
    List<String> endpoints = const [],
    String generatedDate = '',
    String flutterVersion = '',
    String dartVersion = '',
  }) {
    final date = generatedDate.isEmpty
        ? DateTime.now().toString().split(' ')[0]
        : generatedDate;
    final featuresXml = features.isEmpty
        ? '<w:p><w:r><w:t>No features detected. Run arcle feature to create features.</w:t></w:r></w:p>'
        : features
            .map((f) => '<w:p><w:r><w:t>• $f</w:t></w:r></w:p>')
            .join('\n    ');
    final depsXml = dependencies.isEmpty
        ? '<w:p><w:r><w:t>Run flutter pub get to install dependencies.</w:t></w:r></w:p>'
        : dependencies
            .map((d) => '<w:p><w:r><w:t>• $d</w:t></w:r></w:p>')
            .join('\n    ');
    final endpointsXml = endpoints.isEmpty
        ? '<w:p><w:r><w:t>No API endpoints configured.</w:t></w:r></w:p>'
        : endpoints
            .map((e) => '<w:p><w:r><w:t>• $e</w:t></w:r></w:p>')
            .join('\n    ');

    // Word 2003 XML format - compatible with modern Word
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml"
  xmlns:v="urn:schemas-microsoft-com:vml"
  xmlns:w10="urn:schemas-microsoft-com:office:word"
  xmlns:sl="http://schemas.microsoft.com/schemaLibrary/2003/core"
  xmlns:aml="http://schemas.microsoft.com/aml/2001/core"
  xmlns:wx="http://schemas.microsoft.com/office/word/2003/auxHint"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
  w:macrosPresent="no" w:embeddedObjPresent="no" w:ocxPresent="no"
  xml:space="preserve">
  <w:body>
    <!-- COVER PAGE -->
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:b/>
          <w:sz w:val="72"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="72"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>$projectName</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:sz w:val="32"/>
          <w:i/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="32"/>
          <w:i/>
        </w:rPr>
        <w:t>Technical Documentation &amp; UAT Guide</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:sz w:val="28"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="28"/>
        </w:rPr>
        <w:t>Version $version</w:t>
      </w:r>
    </w:p>
    <w:p/>
    <w:p/>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:sz w:val="24"/>
          <w:color w:val="666666"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="24"/>
          <w:color w:val="666666"/>
        </w:rPr>
        <w:t>Generated: $date</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:sz w:val="24"/>
          <w:color w:val="666666"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="24"/>
          <w:color w:val="666666"/>
        </w:rPr>
        <w:t>Generated by ARCLE CLI</w:t>
      </w:r>
    </w:p>
    <w:p><w:r><w:br w:type="page"/></w:r></w:p>
    
    <!-- TABLE OF CONTENTS -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>Table of Contents</w:t>
      </w:r>
    </w:p>
    <w:p><w:r><w:t>1. Executive Summary</w:t></w:r></w:p>
    <w:p><w:r><w:t>2. Project Overview</w:t></w:r></w:p>
    <w:p><w:r><w:t>3. Technical Architecture</w:t></w:r></w:p>
    <w:p><w:r><w:t>4. Feature Modules</w:t></w:r></w:p>
    <w:p><w:r><w:t>5. API Documentation</w:t></w:r></w:p>
    <w:p><w:r><w:t>6. Dependencies &amp; Third-Party Libraries</w:t></w:r></w:p>
    <w:p><w:r><w:t>7. Environment Setup</w:t></w:r></w:p>
    <w:p><w:r><w:t>8. Build &amp; Deployment</w:t></w:r></w:p>
    <w:p><w:r><w:t>9. Testing Strategy</w:t></w:r></w:p>
    <w:p><w:r><w:t>10. UAT Acceptance Criteria</w:t></w:r></w:p>
    <w:p><w:r><w:t>11. Security Considerations</w:t></w:r></w:p>
    <w:p><w:r><w:t>12. Maintenance &amp; Support</w:t></w:r></w:p>
    <w:p><w:r><w:t>Appendix A: CLI Commands Reference</w:t></w:r></w:p>
    <w:p><w:r><w:t>Appendix B: Troubleshooting Guide</w:t></w:r></w:p>
    <w:p><w:r><w:br w:type="page"/></w:r></w:p>
    
    <!-- SECTION 1: EXECUTIVE SUMMARY -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>1. Executive Summary</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r><w:t>This document provides comprehensive technical documentation for the $projectName mobile application. It serves as the primary reference for developers, QA engineers, project managers, and stakeholders involved in the development, testing, and deployment of this application.</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/></w:rPr><w:t>Project Highlights:</w:t></w:r>
    </w:p>
    <w:p><w:r><w:t>• Built with Flutter for cross-platform mobile development (iOS &amp; Android)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Implements Clean Architecture for maintainability and testability</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Uses $stateLabel for state management</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Generated and scaffolded using ARCLE CLI</w:t></w:r></w:p>
    <w:p/>
    
    <!-- SECTION 2: PROJECT OVERVIEW -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>2. Project Overview</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr><w:rPr><w:b/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/></w:rPr><w:t>Project Information</w:t></w:r>
    </w:p>
    <w:tbl>
      <w:tblPr>
        <w:tblW w:w="9000" w:type="dxa"/>
        <w:tblBorders>
          <w:top w:val="single" w:sz="4" w:color="cccccc"/>
          <w:left w:val="single" w:sz="4" w:color="cccccc"/>
          <w:bottom w:val="single" w:sz="4" w:color="cccccc"/>
          <w:right w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideH w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideV w:val="single" w:sz="4" w:color="cccccc"/>
        </w:tblBorders>
      </w:tblPr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Property</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Value</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Project Name</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>$projectName</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Version</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>$version</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>State Management</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>$stateLabel</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Architecture Pattern</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Clean Architecture (Feature-First)</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Flutter Version</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>${flutterVersion.isEmpty ? 'See environment' : flutterVersion}</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Dart SDK</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>${dartVersion.isEmpty ? 'See pubspec.yaml' : dartVersion}</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Target Platforms</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>iOS, Android, Web (optional)</w:t></w:r></w:p></w:tc>
      </w:tr>
    </w:tbl>
    <w:p/>
    
    <!-- SECTION 3: TECHNICAL ARCHITECTURE -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>3. Technical Architecture</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>3.1 Clean Architecture Layers</w:t></w:r>
    </w:p>
    <w:p><w:r><w:t>The application follows Clean Architecture principles with clear separation of concerns:</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Presentation Layer</w:t></w:r></w:p>
    <w:p><w:r><w:t>• UI Screens and Widgets</w:t></w:r></w:p>
    <w:p><w:r><w:t>• State Management ($stateLabel)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• View Models / Controllers / Blocs</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Domain Layer</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Entities (Business Objects)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Use Cases (Business Logic)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Repository Interfaces (Contracts)</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Data Layer</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Repository Implementations</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Data Sources (Remote/Local)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Models (DTOs)</w:t></w:r></w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>3.2 Directory Structure</w:t></w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>lib/</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>├── app/                    # App configuration</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>├── core/                   # Shared utilities</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│   ├── api_client/         # HTTP client</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│   ├── di/                 # Dependency injection</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│   ├── error_handler/      # Error handling</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│   ├── route_handler/      # Navigation</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│   └── utils/              # Helpers</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>├── features/               # Feature modules</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│   └── [feature_name]/</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│       ├── data/</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│       ├── domain/</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>│       └── presentation/</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/></w:rPr><w:t>└── main.dart</w:t></w:r></w:p>
    <w:p/>
    
    <!-- SECTION 4: FEATURE MODULES -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>4. Feature Modules</w:t>
      </w:r>
    </w:p>
    <w:p><w:r><w:t>The following feature modules are implemented in the project:</w:t></w:r></w:p>
    <w:p/>
    $featuresXml
    <w:p/>
    
    <!-- SECTION 5: API DOCUMENTATION -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>5. API Documentation</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>5.1 API Endpoints</w:t></w:r>
    </w:p>
    $endpointsXml
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>5.2 HTTP Client Configuration</w:t></w:r>
    </w:p>
    <w:p><w:r><w:t>• Base URL: Configured in environment files</w:t></w:r></w:p>
    <w:p><w:r><w:t>• HTTP Client: Dio with interceptors</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Authentication: Bearer token in headers</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Timeout: Configurable connection/receive timeouts</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Retry Logic: Automatic retry on failure</w:t></w:r></w:p>
    <w:p/>
    
    <!-- SECTION 6: DEPENDENCIES -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>6. Dependencies &amp; Third-Party Libraries</w:t>
      </w:r>
    </w:p>
    <w:p><w:r><w:t>The following packages are used in this project:</w:t></w:r></w:p>
    <w:p/>
    $depsXml
    <w:p/>
    
    <!-- SECTION 7: ENVIRONMENT SETUP -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>7. Environment Setup</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>7.1 Prerequisites</w:t></w:r>
    </w:p>
    <w:p><w:r><w:t>• Flutter SDK (stable channel)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Dart SDK (bundled with Flutter)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Android Studio / Xcode (for mobile development)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• VS Code or IntelliJ IDEA (recommended IDE)</w:t></w:r></w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>7.2 Initial Setup Steps</w:t></w:r>
    </w:p>
    <w:p><w:r><w:t>1. Clone the repository</w:t></w:r></w:p>
    <w:p><w:r><w:t>2. Run: flutter pub get</w:t></w:r></w:p>
    <w:p><w:r><w:t>3. Configure environment variables in lib/core/env/</w:t></w:r></w:p>
    <w:p><w:r><w:t>4. Run build_runner: dart run build_runner build</w:t></w:r></w:p>
    <w:p><w:r><w:t>5. Run the app: flutter run</w:t></w:r></w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>7.3 Environment Configuration</w:t></w:r>
    </w:p>
    <w:p><w:r><w:t>The app supports multiple environments:</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Development (dev) - Local development with debug tools</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Staging (staging) - Pre-production testing</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Production (prod) - Live environment</w:t></w:r></w:p>
    <w:p/>
    
    <!-- SECTION 8: BUILD & DEPLOYMENT -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>8. Build &amp; Deployment</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>8.1 Android Build</w:t></w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t># Debug APK</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>flutter build apk --debug</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t># Release APK</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>flutter build apk --release</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t># App Bundle (for Play Store)</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>flutter build appbundle --release</w:t></w:r></w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>8.2 iOS Build</w:t></w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t># iOS Archive</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>flutter build ipa --release</w:t></w:r></w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>8.3 Using ARCLE CLI</w:t></w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>arcle build --mode release</w:t></w:r></w:p>
    <w:p/>
    
    <!-- SECTION 9: TESTING STRATEGY -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>9. Testing Strategy</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>9.1 Test Types</w:t></w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Unit Tests</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Test individual functions, methods, and classes</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Located in: test/unit/</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Run: flutter test test/unit/</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Widget Tests</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Test UI components in isolation</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Located in: test/widget/</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Run: flutter test test/widget/</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Integration Tests</w:t></w:r></w:p>
    <w:p><w:r><w:t>• End-to-end testing of complete flows</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Located in: integration_test/</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Run: flutter test integration_test/</w:t></w:r></w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>9.2 Running All Tests</w:t></w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>flutter test</w:t></w:r></w:p>
    <w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>flutter test --coverage</w:t></w:r></w:p>
    <w:p/>
    
    <!-- SECTION 10: UAT ACCEPTANCE CRITERIA -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>10. UAT Acceptance Criteria</w:t>
      </w:r>
    </w:p>
    <w:p><w:r><w:t>This section defines the User Acceptance Testing criteria for release approval.</w:t></w:r></w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>10.1 Functional Requirements</w:t></w:r>
    </w:p>
    <w:tbl>
      <w:tblPr>
        <w:tblW w:w="9000" w:type="dxa"/>
        <w:tblBorders>
          <w:top w:val="single" w:sz="4" w:color="cccccc"/>
          <w:left w:val="single" w:sz="4" w:color="cccccc"/>
          <w:bottom w:val="single" w:sz="4" w:color="cccccc"/>
          <w:right w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideH w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideV w:val="single" w:sz="4" w:color="cccccc"/>
        </w:tblBorders>
      </w:tblPr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>ID</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Requirement</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Priority</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Status</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>UAT-001</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>App launches without errors</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Critical</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass / [ ] Fail</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>UAT-002</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>User authentication works correctly</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Critical</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass / [ ] Fail</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>UAT-003</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Navigation flows are intuitive</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>High</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass / [ ] Fail</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>UAT-004</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Error messages are user-friendly</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Medium</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass / [ ] Fail</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>UAT-005</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Data persists across sessions</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>High</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass / [ ] Fail</w:t></w:r></w:p></w:tc>
      </w:tr>
    </w:tbl>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>10.2 Performance Criteria</w:t></w:r>
    </w:p>
    <w:tbl>
      <w:tblPr>
        <w:tblW w:w="9000" w:type="dxa"/>
        <w:tblBorders>
          <w:top w:val="single" w:sz="4" w:color="cccccc"/>
          <w:left w:val="single" w:sz="4" w:color="cccccc"/>
          <w:bottom w:val="single" w:sz="4" w:color="cccccc"/>
          <w:right w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideH w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideV w:val="single" w:sz="4" w:color="cccccc"/>
        </w:tblBorders>
      </w:tblPr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Metric</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Target</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Actual</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Status</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>App Cold Start</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>&lt; 3 seconds</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>____</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Screen Transition</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>&lt; 300ms</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>____</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>API Response</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>&lt; 2 seconds</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>____</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Memory Usage</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>&lt; 200MB</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>____</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>[ ] Pass</w:t></w:r></w:p></w:tc>
      </w:tr>
    </w:tbl>
    <w:p/>
    <w:p>
      <w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>10.3 Sign-Off</w:t></w:r>
    </w:p>
    <w:tbl>
      <w:tblPr>
        <w:tblW w:w="9000" w:type="dxa"/>
        <w:tblBorders>
          <w:top w:val="single" w:sz="4" w:color="cccccc"/>
          <w:left w:val="single" w:sz="4" w:color="cccccc"/>
          <w:bottom w:val="single" w:sz="4" w:color="cccccc"/>
          <w:right w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideH w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideV w:val="single" w:sz="4" w:color="cccccc"/>
        </w:tblBorders>
      </w:tblPr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Role</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Name</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Signature</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Date</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>QA Lead</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>________________</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>________________</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>____/____/____</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Product Owner</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>________________</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>________________</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>____/____/____</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>Tech Lead</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>________________</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>________________</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>____/____/____</w:t></w:r></w:p></w:tc>
      </w:tr>
    </w:tbl>
    <w:p/>
    
    <!-- SECTION 11: SECURITY -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>11. Security Considerations</w:t>
      </w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Authentication &amp; Authorization</w:t></w:r></w:p>
    <w:p><w:r><w:t>• JWT-based authentication with secure token storage</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Token refresh mechanism for session management</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Secure storage using flutter_secure_storage</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Data Protection</w:t></w:r></w:p>
    <w:p><w:r><w:t>• HTTPS for all API communications</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Certificate pinning (recommended for production)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• No sensitive data in logs or error messages</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Code Security</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Obfuscation enabled for release builds</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Environment variables for sensitive configuration</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Input validation on all user inputs</w:t></w:r></w:p>
    <w:p/>
    
    <!-- SECTION 12: MAINTENANCE -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>12. Maintenance &amp; Support</w:t>
      </w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Regular Maintenance Tasks</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Update dependencies: flutter pub upgrade</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Run code analysis: flutter analyze</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Update SDK: flutter upgrade</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Regenerate DI: arcle auto-gen-di</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Support Contacts</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Technical Lead: [Contact Info]</w:t></w:r></w:p>
    <w:p><w:r><w:t>• DevOps: [Contact Info]</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Product Owner: [Contact Info]</w:t></w:r></w:p>
    <w:p/>
    
    <!-- APPENDIX A: CLI COMMANDS -->
    <w:p><w:r><w:br w:type="page"/></w:r></w:p>
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>Appendix A: ARCLE CLI Commands Reference</w:t>
      </w:r>
    </w:p>
    <w:tbl>
      <w:tblPr>
        <w:tblW w:w="9000" w:type="dxa"/>
        <w:tblBorders>
          <w:top w:val="single" w:sz="4" w:color="cccccc"/>
          <w:left w:val="single" w:sz="4" w:color="cccccc"/>
          <w:bottom w:val="single" w:sz="4" w:color="cccccc"/>
          <w:right w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideH w:val="single" w:sz="4" w:color="cccccc"/>
          <w:insideV w:val="single" w:sz="4" w:color="cccccc"/>
        </w:tblBorders>
      </w:tblPr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Command</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Description</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>arcle create &lt;name&gt;</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Create a new Flutter project with clean architecture</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>arcle init</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Initialize ARCLE in an existing Flutter project</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>arcle feature &lt;name&gt;</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Generate a new feature module</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>arcle gen-di</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Generate dependency injection configuration</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>arcle auto-gen-di</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Auto-generate DI using build_runner</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>arcle build</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Build APK/IPA with specified mode</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/></w:rPr><w:t>arcle gen-doc</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>Generate project documentation</w:t></w:r></w:p></w:tc>
      </w:tr>
    </w:tbl>
    <w:p/>
    
    <!-- APPENDIX B: TROUBLESHOOTING -->
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="36"/>
          <w:color w:val="1a73e8"/>
        </w:rPr>
        <w:t>Appendix B: Troubleshooting Guide</w:t>
      </w:r>
    </w:p>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Common Issues &amp; Solutions</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Build Errors</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Run: flutter clean &amp;&amp; flutter pub get</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Regenerate code: dart run build_runner build --delete-conflicting-outputs</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>DI Not Working</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Ensure @injectable annotation on classes</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Run: arcle auto-gen-di</w:t></w:r></w:p>
    <w:p/>
    <w:p><w:r><w:rPr><w:b/></w:rPr><w:t>API Connection Issues</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Check BASE_URL in environment configuration</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Verify network permissions in AndroidManifest.xml / Info.plist</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Check if backend server is running</w:t></w:r></w:p>
    <w:p/>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:color w:val="999999"/>
          <w:sz w:val="20"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:color w:val="999999"/>
          <w:sz w:val="20"/>
        </w:rPr>
        <w:t>--- End of Document ---</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:color w:val="999999"/>
          <w:sz w:val="20"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:color w:val="999999"/>
          <w:sz w:val="20"/>
        </w:rPr>
        <w:t>Generated by ARCLE CLI | $date</w:t>
      </w:r>
    </w:p>
  </w:body>
</w:wordDocument>
''';
  }

  static String projectDocLatex({
    required String projectName,
    required String version,
    required String stateLabel,
    String description = '',
    List<String> features = const [],
    List<String> dependencies = const [],
    List<String> endpoints = const [],
    String generatedDate = '',
    String flutterVersion = '',
    String dartVersion = '',
  }) {
    final safeName = _latexEscape(projectName);
    final safeVersion = _latexEscape(version);
    final safeState = _latexEscape(stateLabel);
    final date = generatedDate.isEmpty
        ? DateTime.now().toString().split(' ')[0]
        : generatedDate;
    final featuresLatex = features.isEmpty
        ? '\\item No features detected. Run arcle feature to create features.'
        : features.map((f) => '\\item ${_latexEscape(f)}').join('\n  ');
    final depsLatex = dependencies.isEmpty
        ? '\\item Run flutter pub get to install dependencies.'
        : dependencies
            .map((d) => '\\item \\texttt{${_latexEscape(d)}}')
            .join('\n  ');
    final endpointsLatex = endpoints.isEmpty
        ? '\\item No API endpoints configured.'
        : endpoints
            .map((e) => '\\item \\texttt{${_latexEscape(e)}}')
            .join('\n  ');

    return r'''
\documentclass[11pt,a4paper]{article}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage{listings}
\usepackage{graphicx}

\definecolor{primaryblue}{RGB}{26,115,232}
\definecolor{codegray}{RGB}{245,245,245}

\hypersetup{
    colorlinks=true,
    linkcolor=primaryblue,
    urlcolor=primaryblue,
}

\lstset{
    backgroundcolor=\color{codegray},
    basicstyle=\ttfamily\small,
    breaklines=true,
    frame=single,
    rulecolor=\color{gray}
}

\pagestyle{fancy}
\fancyhf{}
\rhead{''' +
        safeName +
        r''' v''' +
        safeVersion +
        r'''}
\lhead{Technical Documentation}
\rfoot{Page \thepage}
\lfoot{Generated by ARCLE CLI}

\setlist[itemize]{noitemsep,topsep=2pt}

\begin{document}

% COVER PAGE
\begin{titlepage}
\centering
\vspace*{2cm}
{\Huge\bfseries\color{primaryblue} ''' +
        safeName +
        r'''}\\[1cm]
{\Large Technical Documentation \& UAT Guide}\\[0.5cm]
{\large Version ''' +
        safeVersion +
        r'''}\\[2cm]
\vfill
{\large Generated: ''' +
        date +
        r'''}\\[0.3cm]
{\small Generated by ARCLE CLI}
\end{titlepage}

% TABLE OF CONTENTS
\tableofcontents
\newpage

% SECTION 1: EXECUTIVE SUMMARY
\section{Executive Summary}
This document provides comprehensive technical documentation for the ''' +
        safeName +
        r''' mobile application. It serves as the primary reference for developers, QA engineers, project managers, and stakeholders involved in the development, testing, and deployment of this application.

\subsection*{Project Highlights}
\begin{itemize}
  \item Built with Flutter for cross-platform mobile development (iOS \& Android)
  \item Implements Clean Architecture for maintainability and testability
  \item Uses ''' +
        safeState +
        r''' for state management
  \item Generated and scaffolded using ARCLE CLI
\end{itemize}

% SECTION 2: PROJECT OVERVIEW
\section{Project Overview}

\subsection{Project Information}
\begin{longtable}{|l|l|}
\hline
\textbf{Property} & \textbf{Value} \\
\hline
Project Name & ''' +
        safeName +
        r''' \\
Version & ''' +
        safeVersion +
        r''' \\
State Management & ''' +
        safeState +
        r''' \\
Architecture Pattern & Clean Architecture (Feature-First) \\
Target Platforms & iOS, Android, Web (optional) \\
\hline
\end{longtable}

% SECTION 3: TECHNICAL ARCHITECTURE
\section{Technical Architecture}

\subsection{Clean Architecture Layers}
The application follows Clean Architecture principles with clear separation of concerns:

\textbf{Presentation Layer}
\begin{itemize}
  \item UI Screens and Widgets
  \item State Management (''' +
        safeState +
        r''')
  \item View Models / Controllers / Blocs
\end{itemize}

\textbf{Domain Layer}
\begin{itemize}
  \item Entities (Business Objects)
  \item Use Cases (Business Logic)
  \item Repository Interfaces (Contracts)
\end{itemize}

\textbf{Data Layer}
\begin{itemize}
  \item Repository Implementations
  \item Data Sources (Remote/Local)
  \item Models (DTOs)
\end{itemize}

\subsection{Directory Structure}
\begin{lstlisting}
lib/
|-- app/                    # App configuration
|-- core/                   # Shared utilities
|   |-- api_client/         # HTTP client
|   |-- di/                 # Dependency injection
|   |-- error_handler/      # Error handling
|   |-- route_handler/      # Navigation
|   `-- utils/              # Helpers
|-- features/               # Feature modules
|   `-- [feature_name]/
|       |-- data/
|       |-- domain/
|       `-- presentation/
`-- main.dart
\end{lstlisting}

% SECTION 4: FEATURE MODULES
\section{Feature Modules}
The following feature modules are implemented in the project:

\begin{itemize}
  ''' +
        featuresLatex +
        r'''
\end{itemize}

% SECTION 5: API DOCUMENTATION
\section{API Documentation}

\subsection{API Endpoints}
\begin{itemize}
  ''' +
        endpointsLatex +
        r'''
\end{itemize}

\subsection{HTTP Client Configuration}
\begin{itemize}
  \item Base URL: Configured in environment files
  \item HTTP Client: Dio with interceptors
  \item Authentication: Bearer token in headers
  \item Timeout: Configurable connection/receive timeouts
  \item Retry Logic: Automatic retry on failure
\end{itemize}

% SECTION 6: DEPENDENCIES
\section{Dependencies \& Third-Party Libraries}
The following packages are used in this project:

\begin{itemize}
  ''' +
        depsLatex +
        r'''
\end{itemize}

% SECTION 7: ENVIRONMENT SETUP
\section{Environment Setup}

\subsection{Prerequisites}
\begin{itemize}
  \item Flutter SDK (stable channel)
  \item Dart SDK (bundled with Flutter)
  \item Android Studio / Xcode (for mobile development)
  \item VS Code or IntelliJ IDEA (recommended IDE)
\end{itemize}

\subsection{Initial Setup Steps}
\begin{enumerate}
  \item Clone the repository
  \item Run: \texttt{flutter pub get}
  \item Configure environment variables in \texttt{lib/core/env/}
  \item Run build\_runner: \texttt{dart run build\_runner build}
  \item Run the app: \texttt{flutter run}
\end{enumerate}

\subsection{Environment Configuration}
The app supports multiple environments:
\begin{itemize}
  \item Development (dev) - Local development with debug tools
  \item Staging (staging) - Pre-production testing
  \item Production (prod) - Live environment
\end{itemize}

% SECTION 8: BUILD & DEPLOYMENT
\section{Build \& Deployment}

\subsection{Android Build}
\begin{lstlisting}
# Debug APK
flutter build apk --debug

# Release APK
flutter build apk --release

# App Bundle (for Play Store)
flutter build appbundle --release
\end{lstlisting}

\subsection{iOS Build}
\begin{lstlisting}
# iOS Archive
flutter build ipa --release
\end{lstlisting}

\subsection{Using ARCLE CLI}
\begin{lstlisting}
arcle build --mode release
\end{lstlisting}

% SECTION 9: TESTING STRATEGY
\section{Testing Strategy}

\subsection{Test Types}
\textbf{Unit Tests}
\begin{itemize}
  \item Test individual functions, methods, and classes
  \item Located in: \texttt{test/unit/}
  \item Run: \texttt{flutter test test/unit/}
\end{itemize}

\textbf{Widget Tests}
\begin{itemize}
  \item Test UI components in isolation
  \item Located in: \texttt{test/widget/}
  \item Run: \texttt{flutter test test/widget/}
\end{itemize}

\textbf{Integration Tests}
\begin{itemize}
  \item End-to-end testing of complete flows
  \item Located in: \texttt{integration\_test/}
  \item Run: \texttt{flutter test integration\_test/}
\end{itemize}

\subsection{Running All Tests}
\begin{lstlisting}
flutter test
flutter test --coverage
\end{lstlisting}

% SECTION 10: UAT ACCEPTANCE CRITERIA
\section{UAT Acceptance Criteria}
This section defines the User Acceptance Testing criteria for release approval.

\subsection{Functional Requirements}
\begin{longtable}{|l|p{6cm}|l|l|}
\hline
\textbf{ID} & \textbf{Requirement} & \textbf{Priority} & \textbf{Status} \\
\hline
UAT-001 & App launches without errors & Critical & $\square$ Pass \\
UAT-002 & User authentication works correctly & Critical & $\square$ Pass \\
UAT-003 & Navigation flows are intuitive & High & $\square$ Pass \\
UAT-004 & Error messages are user-friendly & Medium & $\square$ Pass \\
UAT-005 & Data persists across sessions & High & $\square$ Pass \\
\hline
\end{longtable}

\subsection{Performance Criteria}
\begin{longtable}{|l|l|l|l|}
\hline
\textbf{Metric} & \textbf{Target} & \textbf{Actual} & \textbf{Status} \\
\hline
App Cold Start & $<$ 3 seconds & \_\_\_\_ & $\square$ Pass \\
Screen Transition & $<$ 300ms & \_\_\_\_ & $\square$ Pass \\
API Response & $<$ 2 seconds & \_\_\_\_ & $\square$ Pass \\
Memory Usage & $<$ 200MB & \_\_\_\_ & $\square$ Pass \\
\hline
\end{longtable}

\subsection{Sign-Off}
\begin{longtable}{|l|l|l|l|}
\hline
\textbf{Role} & \textbf{Name} & \textbf{Signature} & \textbf{Date} \\
\hline
QA Lead & \_\_\_\_\_\_\_\_ & \_\_\_\_\_\_\_\_ & \_\_/\_\_/\_\_\_\_ \\
Product Owner & \_\_\_\_\_\_\_\_ & \_\_\_\_\_\_\_\_ & \_\_/\_\_/\_\_\_\_ \\
Tech Lead & \_\_\_\_\_\_\_\_ & \_\_\_\_\_\_\_\_ & \_\_/\_\_/\_\_\_\_ \\
\hline
\end{longtable}

% SECTION 11: SECURITY
\section{Security Considerations}

\textbf{Authentication \& Authorization}
\begin{itemize}
  \item JWT-based authentication with secure token storage
  \item Token refresh mechanism for session management
  \item Secure storage using flutter\_secure\_storage
\end{itemize}

\textbf{Data Protection}
\begin{itemize}
  \item HTTPS for all API communications
  \item Certificate pinning (recommended for production)
  \item No sensitive data in logs or error messages
\end{itemize}

\textbf{Code Security}
\begin{itemize}
  \item Obfuscation enabled for release builds
  \item Environment variables for sensitive configuration
  \item Input validation on all user inputs
\end{itemize}

% SECTION 12: MAINTENANCE
\section{Maintenance \& Support}

\textbf{Regular Maintenance Tasks}
\begin{itemize}
  \item Update dependencies: \texttt{flutter pub upgrade}
  \item Run code analysis: \texttt{flutter analyze}
  \item Update SDK: \texttt{flutter upgrade}
  \item Regenerate DI: \texttt{arcle auto-gen-di}
\end{itemize}

\textbf{Support Contacts}
\begin{itemize}
  \item Technical Lead: [Contact Info]
  \item DevOps: [Contact Info]
  \item Product Owner: [Contact Info]
\end{itemize}

% APPENDIX A: CLI COMMANDS
\newpage
\appendix
\section{ARCLE CLI Commands Reference}

\begin{longtable}{|l|p{8cm}|}
\hline
\textbf{Command} & \textbf{Description} \\
\hline
\texttt{arcle create <name>} & Create a new Flutter project with clean architecture \\
\texttt{arcle init} & Initialize ARCLE in an existing Flutter project \\
\texttt{arcle feature <name>} & Generate a new feature module \\
\texttt{arcle gen-di} & Generate dependency injection configuration \\
\texttt{arcle auto-gen-di} & Auto-generate DI using build\_runner \\
\texttt{arcle build} & Build APK/IPA with specified mode \\
\texttt{arcle gen-doc} & Generate project documentation \\
\hline
\end{longtable}

% APPENDIX B: TROUBLESHOOTING
\section{Troubleshooting Guide}

\textbf{Build Errors}
\begin{itemize}
  \item Run: \texttt{flutter clean \&\& flutter pub get}
  \item Regenerate code: \texttt{dart run build\_runner build --delete-conflicting-outputs}
\end{itemize}

\textbf{DI Not Working}
\begin{itemize}
  \item Ensure \texttt{@injectable} annotation on classes
  \item Run: \texttt{arcle auto-gen-di}
\end{itemize}

\textbf{API Connection Issues}
\begin{itemize}
  \item Check BASE\_URL in environment configuration
  \item Verify network permissions in AndroidManifest.xml / Info.plist
  \item Check if backend server is running
\end{itemize}

\vfill
\begin{center}
--- End of Document ---\\
Generated by ARCLE CLI | ''' +
        date +
        r'''
\end{center}

\end{document}
''';
  }

  static String projectDocMarkdown({
    required String projectName,
    required String version,
    required String stateLabel,
    String description = '',
    List<String> features = const [],
    List<String> dependencies = const [],
    List<String> endpoints = const [],
    String generatedDate = '',
    String flutterVersion = '',
    String dartVersion = '',
  }) {
    final date = generatedDate.isEmpty
        ? DateTime.now().toString().split(' ')[0]
        : generatedDate;
    final featuresMarkdown = features.isEmpty
        ? '- No features detected. Run `arcle feature` to create features.'
        : features.map((f) => '- $f').join('\n');
    final depsMarkdown = dependencies.isEmpty
        ? '- Run `flutter pub get` to install dependencies.'
        : dependencies.map((d) => '- `$d`').join('\n');
    final endpointsMarkdown = endpoints.isEmpty
        ? '- No API endpoints configured.'
        : endpoints.map((e) => '- `$e`').join('\n');

    return '''
# $projectName

## Technical Documentation & UAT Guide

**Version:** $version  
**Generated:** $date  
**Generated by:** ARCLE CLI

---

## Table of Contents

1. [Executive Summary](#executive-summary)
2. [Project Overview](#project-overview)
3. [Technical Architecture](#technical-architecture)
4. [Feature Modules](#feature-modules)
5. [API Documentation](#api-documentation)
6. [Dependencies](#dependencies)
7. [Environment Setup](#environment-setup)
8. [Build & Deployment](#build--deployment)
9. [Testing Strategy](#testing-strategy)
10. [UAT Acceptance Criteria](#uat-acceptance-criteria)
11. [Security Considerations](#security-considerations)
12. [Maintenance & Support](#maintenance--support)

---

## Executive Summary

This document provides comprehensive technical documentation for the **$projectName** mobile application. It serves as the primary reference for developers, QA engineers, project managers, and stakeholders.

### Project Highlights
- Built with **Flutter** for cross-platform mobile development (iOS & Android)
- Implements **Clean Architecture** for maintainability and testability
- Uses **$stateLabel** for state management
- Generated and scaffolded using **ARCLE CLI**

---

## Project Overview

| Property | Value |
|----------|-------|
| Project Name | $projectName |
| Version | $version |
| State Management | $stateLabel |
| Architecture Pattern | Clean Architecture (Feature-First) |
| Flutter Version | ${flutterVersion.isEmpty ? 'See environment' : flutterVersion} |
| Dart SDK | ${dartVersion.isEmpty ? 'See pubspec.yaml' : dartVersion} |
| Target Platforms | iOS, Android, Web (optional) |

---

## Technical Architecture

### Clean Architecture Layers

**Presentation Layer**
- UI Screens and Widgets
- State Management ($stateLabel)
- View Models / Controllers / Blocs

**Domain Layer**
- Entities (Business Objects)
- Use Cases (Business Logic)
- Repository Interfaces (Contracts)

**Data Layer**
- Repository Implementations
- Data Sources (Remote/Local)
- Models (DTOs)

### Directory Structure

```
lib/
├── app/                    # App configuration
├── core/                   # Shared utilities
│   ├── api_client/         # HTTP client
│   ├── di/                 # Dependency injection
│   ├── error_handler/      # Error handling
│   ├── route_handler/      # Navigation
│   └── utils/              # Helpers
├── features/               # Feature modules
│   └── [feature_name]/
│       ├── data/
│       ├── domain/
│       └── presentation/
└── main.dart
```

---

## Feature Modules

$featuresMarkdown

---

## API Documentation

### API Endpoints

$endpointsMarkdown

### HTTP Client Configuration
- **Base URL:** Configured in environment files
- **HTTP Client:** Dio with interceptors
- **Authentication:** Bearer token in headers
- **Timeout:** Configurable connection/receive timeouts
- **Retry Logic:** Automatic retry on failure

---

## Dependencies

$depsMarkdown

---

## Environment Setup

### Prerequisites
- Flutter SDK (stable channel)
- Dart SDK (bundled with Flutter)
- Android Studio / Xcode (for mobile development)
- VS Code or IntelliJ IDEA (recommended IDE)

### Initial Setup Steps
1. Clone the repository
2. Run: `flutter pub get`
3. Configure environment variables in `lib/core/env/`
4. Run build_runner: `dart run build_runner build`
5. Run the app: `flutter run`

### Environment Configuration
- **Development (dev)** - Local development with debug tools
- **Staging (staging)** - Pre-production testing
- **Production (prod)** - Live environment

---

## Build & Deployment

### Android Build

```bash
# Debug APK
flutter build apk --debug

# Release APK
flutter build apk --release

# App Bundle (for Play Store)
flutter build appbundle --release
```

### iOS Build

```bash
# iOS Archive
flutter build ipa --release
```

### Using ARCLE CLI

```bash
arcle build --mode release
```

---

## Testing Strategy

### Unit Tests
- Test individual functions, methods, and classes
- Located in: `test/unit/`
- Run: `flutter test test/unit/`

### Widget Tests
- Test UI components in isolation
- Located in: `test/widget/`
- Run: `flutter test test/widget/`

### Integration Tests
- End-to-end testing of complete flows
- Located in: `integration_test/`
- Run: `flutter test integration_test/`

### Running All Tests

```bash
flutter test
flutter test --coverage
```

---

## UAT Acceptance Criteria

### Functional Requirements

| ID | Requirement | Priority | Status |
|----|-------------|----------|--------|
| UAT-001 | App launches without errors | Critical | ☐ Pass / ☐ Fail |
| UAT-002 | User authentication works correctly | Critical | ☐ Pass / ☐ Fail |
| UAT-003 | Navigation flows are intuitive | High | ☐ Pass / ☐ Fail |
| UAT-004 | Error messages are user-friendly | Medium | ☐ Pass / ☐ Fail |
| UAT-005 | Data persists across sessions | High | ☐ Pass / ☐ Fail |

### Performance Criteria

| Metric | Target | Actual | Status |
|--------|--------|--------|--------|
| App Cold Start | < 3 seconds | ____ | ☐ Pass |
| Screen Transition | < 300ms | ____ | ☐ Pass |
| API Response | < 2 seconds | ____ | ☐ Pass |
| Memory Usage | < 200MB | ____ | ☐ Pass |

### Sign-Off

| Role | Name | Signature | Date |
|------|------|-----------|------|
| QA Lead | ________ | ________ | __ /__ /____ |
| Product Owner | ________ | ________ | __ /__ /____ |
| Tech Lead | ________ | ________ | __ /__ /____ |

---

## Security Considerations

### Authentication & Authorization
- JWT-based authentication with secure token storage
- Token refresh mechanism for session management
- Secure storage using flutter_secure_storage

### Data Protection
- HTTPS for all API communications
- Certificate pinning (recommended for production)
- No sensitive data in logs or error messages

### Code Security
- Obfuscation enabled for release builds
- Environment variables for sensitive configuration
- Input validation on all user inputs

---

## Maintenance & Support

### Regular Maintenance Tasks
- Update dependencies: `flutter pub upgrade`
- Run code analysis: `flutter analyze`
- Update SDK: `flutter upgrade`
- Regenerate DI: `arcle auto-gen-di`

### Support Contacts
- **Technical Lead:** [Contact Info]
- **DevOps:** [Contact Info]
- **Product Owner:** [Contact Info]

---

## Appendix A: ARCLE CLI Commands Reference

| Command | Description |
|---------|-------------|
| `arcle create <name>` | Create a new Flutter project with clean architecture |
| `arcle init` | Initialize ARCLE in an existing Flutter project |
| `arcle feature <name>` | Generate a new feature module |
| `arcle gen-di` | Generate dependency injection configuration |
| `arcle auto-gen-di` | Auto-generate DI using build_runner |
| `arcle build` | Build APK/IPA with specified mode |
| `arcle gen-doc` | Generate project documentation |

---

## Appendix B: Troubleshooting Guide

### Build Errors
- Run: `flutter clean && flutter pub get`
- Regenerate code: `dart run build_runner build --delete-conflicting-outputs`

### DI Not Working
- Ensure `@injectable` annotation on classes
- Run: `arcle auto-gen-di`

### API Connection Issues
- Check BASE_URL in environment configuration
- Verify network permissions in AndroidManifest.xml / Info.plist
- Check if backend server is running

---

*End of Document*  
*Generated by ARCLE CLI | $date*
''';
  }

  static String _latexEscape(String input) {
    return input
        .replaceAll('\\', r'\textbackslash{}')
        .replaceAll('&', r'\&')
        .replaceAll('%', r'\%')
        .replaceAll('\$', r'\$')
        .replaceAll('#', r'\#')
        .replaceAll('_', r'\_')
        .replaceAll('{', r'\{')
        .replaceAll('}', r'\}')
        .replaceAll('~', r'\textasciitilde{}')
        .replaceAll('^', r'\textasciicircum{}');
  }
}
