class DocsTemplates {
  static String projectDocLatex({
    required String projectName,
    required String version,
    required String stateLabel,
  }) {
    final safeName = _latexEscape(projectName);
    final safeVersion = _latexEscape(version);
    final safeState = _latexEscape(stateLabel);
    return r'''
\documentclass[11pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\usepackage{enumitem}
\setlist[itemize]{noitemsep,topsep=2pt}
\begin{document}
\begin{center}
{\LARGE ARCLE Project Documentation}\\[6pt]
{\large ''' +
        safeName +
        r''' \textit{v}''' +
        safeVersion +
        r'''}\\[6pt]
\end{center}

\section*{Project Summary}
\begin{itemize}
  \item \textbf{Name}: ''' +
        safeName +
        r'''
  \item \textbf{Version}: ''' +
        safeVersion +
        r'''
  \item \textbf{State Management}: ''' +
        safeState +
        r'''
  \item \textbf{Architecture}: Clean Architecture (feature-first)
  \item \textbf{Generated By}: ARCLE CLI
\end{itemize}

\section*{Quick Start}
\begin{itemize}
  \item Install dependencies: \texttt{flutter pub get}
  \item Run the app: \texttt{flutter run}
\end{itemize}

\section*{Key Commands}
\begin{itemize}
  \item Create a feature: \texttt{arcle feature <feature\_name>}
  \item Refresh DI: \texttt{arcle auto-gen-di}
  \item Generate docs: \texttt{arcle gen-doc}
  \item Build APK: \texttt{arcle build --mode release}
\end{itemize}

\section*{Notes}
\begin{itemize}
  \item Keep domain logic isolated from UI.
  \item Run DI generation after adding injectable services.
\end{itemize}

\end{document}
''';
  }

  static String projectDocMarkdown({
    required String projectName,
    required String version,
    required String stateLabel,
  }) {
    return '''
# ARCLE Project Documentation

## Project Summary
- Name: $projectName
- Version: $version
- State Management: $stateLabel
- Architecture: Clean Architecture (feature-first)
- Generated By: ARCLE CLI

## Quick Start
- Install dependencies: `flutter pub get`
- Run the app: `flutter run`

## Key Commands
- Create a feature: `arcle feature <feature_name>`
- Refresh DI: `arcle auto-gen-di`
- Generate docs: `arcle gen-doc`
- Build APK: `arcle build --mode release`

## Notes
- Keep domain logic isolated from UI.
- Run DI generation after adding injectable services.
''';
  }

  static String _latexEscape(String input) {
    return input
        .replaceAll('\\', r'\textbackslash{}')
        .replaceAll('&', r'\&')
        .replaceAll('%', r'\%')
        .replaceAll('\$', r'\$')
        .replaceAll('#', r'\#')
        .replaceAll('_', r'\_')
        .replaceAll('{', r'\{')
        .replaceAll('}', r'\}')
        .replaceAll('~', r'\textasciitilde{}')
        .replaceAll('^', r'\textasciicircum{}');
  }
}
