class DocsTemplates {
  static String projectDocWord({
    required String projectName,
    required String version,
    required String stateLabel,
  }) {
    // Word 2003 XML format - compatible with modern Word
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml"
  xmlns:v="urn:schemas-microsoft-com:vml"
  xmlns:w10="urn:schemas-microsoft-com:office:word"
  xmlns:sl="http://schemas.microsoft.com/schemaLibrary/2003/core"
  xmlns:aml="http://schemas.microsoft.com/aml/2001/core"
  xmlns:wx="http://schemas.microsoft.com/office/word/2003/auxHint"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
  w:macrosPresent="no" w:embeddedObjPresent="no" w:ocxPresent="no"
  xml:space="preserve">
  <w:body>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:b/>
          <w:sz w:val="48"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="48"/>
        </w:rPr>
        <w:t>ARCLE Project Documentation</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:jc w:val="center"/>
        <w:rPr>
          <w:sz w:val="28"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="28"/>
        </w:rPr>
        <w:t>$projectName v$version</w:t>
      </w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
        </w:rPr>
        <w:t>Project Summary</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r><w:t>Name: $projectName</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>Version: $version</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>State Management: $stateLabel</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>Architecture: Clean Architecture (feature-first)</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>Generated By: ARCLE CLI</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
        </w:rPr>
        <w:t>Quick Start</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r><w:t>1. Install dependencies: flutter pub get</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>2. Run the app: flutter run</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
        </w:rPr>
        <w:t>Key Commands</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r><w:t>Create a feature: arcle feature &lt;feature_name&gt;</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>Refresh DI: arcle auto-gen-di</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>Generate docs: arcle gen-doc</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>Build APK: arcle build --mode release</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:pPr>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b/>
          <w:sz w:val="32"/>
        </w:rPr>
        <w:t>Notes</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r><w:t>- Keep domain logic isolated from UI.</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:t>- Run DI generation after adding injectable services.</w:t></w:r>
    </w:p>
  </w:body>
</w:wordDocument>
''';
  }

  static String projectDocLatex({
    required String projectName,
    required String version,
    required String stateLabel,
  }) {
    final safeName = _latexEscape(projectName);
    final safeVersion = _latexEscape(version);
    final safeState = _latexEscape(stateLabel);
    return r'''
\documentclass[11pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\usepackage{enumitem}
\setlist[itemize]{noitemsep,topsep=2pt}
\begin{document}
\begin{center}
{\LARGE ARCLE Project Documentation}\\[6pt]
{\large ''' +
        safeName +
        r''' \textit{v}''' +
        safeVersion +
        r'''}\\[6pt]
\end{center}

\section*{Project Summary}
\begin{itemize}
  \item \textbf{Name}: ''' +
        safeName +
        r'''
  \item \textbf{Version}: ''' +
        safeVersion +
        r'''
  \item \textbf{State Management}: ''' +
        safeState +
        r'''
  \item \textbf{Architecture}: Clean Architecture (feature-first)
  \item \textbf{Generated By}: ARCLE CLI
\end{itemize}

\section*{Quick Start}
\begin{itemize}
  \item Install dependencies: \texttt{flutter pub get}
  \item Run the app: \texttt{flutter run}
\end{itemize}

\section*{Key Commands}
\begin{itemize}
  \item Create a feature: \texttt{arcle feature <feature\_name>}
  \item Refresh DI: \texttt{arcle auto-gen-di}
  \item Generate docs: \texttt{arcle gen-doc}
  \item Build APK: \texttt{arcle build --mode release}
\end{itemize}

\section*{Notes}
\begin{itemize}
  \item Keep domain logic isolated from UI.
  \item Run DI generation after adding injectable services.
\end{itemize}

\end{document}
''';
  }

  static String projectDocMarkdown({
    required String projectName,
    required String version,
    required String stateLabel,
  }) {
    return '''
# ARCLE Project Documentation

## Project Summary
- Name: $projectName
- Version: $version
- State Management: $stateLabel
- Architecture: Clean Architecture (feature-first)
- Generated By: ARCLE CLI

## Quick Start
- Install dependencies: `flutter pub get`
- Run the app: `flutter run`

## Key Commands
- Create a feature: `arcle feature <feature_name>`
- Refresh DI: `arcle auto-gen-di`
- Generate docs: `arcle gen-doc`
- Build APK: `arcle build --mode release`

## Notes
- Keep domain logic isolated from UI.
- Run DI generation after adding injectable services.
''';
  }

  static String _latexEscape(String input) {
    return input
        .replaceAll('\\', r'\textbackslash{}')
        .replaceAll('&', r'\&')
        .replaceAll('%', r'\%')
        .replaceAll('\$', r'\$')
        .replaceAll('#', r'\#')
        .replaceAll('_', r'\_')
        .replaceAll('{', r'\{')
        .replaceAll('}', r'\}')
        .replaceAll('~', r'\textasciitilde{}')
        .replaceAll('^', r'\textasciicircum{}');
  }
}
